#app.yaml
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: chef
  CLOUD_SQL_PASSWORD: food
  CLOUD_SQL_DATABASE_NAME: omniscient
  CLOUD_SQL_CONNECTION_NAME: /cloudsql/cs-411-nullpointers:us-central1:testbed 

